import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/navbar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import theme from "@/theme";
import { ThemeProvider } from "@mui/material/styles";
import MiniDrawer from "./Components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" ">
        <div className="">
          <Navbar />
        </div>

        <div className="mt-10">
          <MiniDrawer />
        </div>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
